litreview/litreview/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
import authentication.views
import blog.views

urlpatterns = [
    path('admin/', admin.site.urls),
    # urls.py
    path("login/", authentication.views.LoginPageView.as_view(), name='login'),
    path('logout/', authentication.views.logout_user, name='logout'),
    path('flow/', blog.views.flow, name='flow'),
    path('review_in_response/<int:ticket_id>', blog.views.review_in_response, name='review_in_response'),
    path('review_not_in_response/', blog.views.review_not_in_response,
         name='review_not_in_response'),
    path('edit_review_in_response/<int:review_id>', blog.views.edit_review_in_response,
         name='edit_review_in_response'),
    path('edit_ticket_not_response/<int:ticket_id>', blog.views.edit_ticket_not_response,
         name='edit_ticket_not_response'),
    path('edit_ticket_not_response1/<int:ticket_id>', blog.views.edit_ticket_not_response1,
         name='edit_ticket_not_response1'),
    path('ticket_delete/<int:ticket_id>', blog.views.ticket_delete, name='ticket_delete'),
    path('review_delete/<int:review_id>', blog.views.review_delete, name='review_delete'),
    path('image_question/<int:ticket_id>', blog.views.image_question, name='image_question'),
    path('posts/', blog.views.posts, name='posts'),
    path('subscriptions/', blog.views.follow_users, name='subscriptions'),
    path('create_ticket/', blog.views.create_ticket, name='create_ticket'),
    path('signup/', authentication.views.SignUpPage.as_view(), name='signup'),
    path('success/', authentication.views.registration_success, name='success'),
    path('password_reset_form/', authentication.views.CustomPasswordResetView.as_view(), name='password_reset_form'),
    path('password_reset_email/', authentication.views.CustomPasswordResetView.as_view(), name='password_reset_email'),
    path('password_reset_confirm/<uidb64>/<token>/',
         authentication.views.CustomPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password_reset_complete/', authentication.views.password_reset_complete, name='password_reset_complete'),
    path('password_reset_done/', authentication.views.password_reset_done, name='password_reset_done'),

]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

litreview/blog/models.py
from django.conf import settings
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator


class Photo(models.Model):
    objects = models.Manager()
    image = models.ImageField()
    uploader = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)


# Créer un ticket (Demander une critique)
class Ticket(models.Model):
    objects = models.Manager()
    photo = models.ForeignKey(Photo, null=True, on_delete=models.CASCADE, blank=True)
    title = models.CharField(max_length=128)
    description = models.TextField(max_length=8192, blank=True)
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    response = models.CharField(max_length=1, default='0')


# Créer une critique (En réponse ou Pas en réponse à un ticket)
class Review(models.Model):
    objects = models.Manager()
    ticket = models.ForeignKey(to=Ticket, on_delete=models.CASCADE, null=True, blank=True)
    rating = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(5)])
    headline = models.CharField(max_length=128)
    body = models.TextField(max_length=8192, blank=True)
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)

litreview/blog/forms.py
from django import forms
from . import models
from django.contrib.auth import get_user_model

User = get_user_model()


class PhotoForm(forms.ModelForm):
    image = forms.ImageField(label='Image')

    class Meta:
        model = models.Photo
        fields = ['image']


class TicketForm(forms.ModelForm):
    title = forms.CharField(max_length=128, label='Titre')
    description = forms.CharField(max_length=8192, label='Description')

    class Meta:
        model = models.Ticket
        fields = ['title', 'description']


class ReviewForm(forms.ModelForm):
    headline = forms.CharField(max_length=128, label='Titre')
    rating = forms.CheckboxInput()
    body = forms.CharField(max_length=8192, label='Commentaire')

    class Meta:
        model = models.Review
        fields = ['headline', 'rating', 'body', 'ticket']


# litreview\blog\forms.py
class FollowUsersForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['following']


# litreview\blog\forms.py
class DeleteFollowingForm(forms.Form):
    following_to_delete = forms.ModelChoiceField(queryset=User.objects.none(), empty_label=None)

    def __init__(self, *args, user=None):
        super().__init__(*args)
        if user is not None:
            self.fields['following_to_delete'].queryset = user.following.all()

litreview/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from . import forms, models
from django.contrib.auth.decorators import login_required
from itertools import chain


@login_required
def flow(request):
    tickets_user = models.Ticket.objects.filter(user=request.user)
    tickets_user_follow = models.Ticket.objects.filter(user__in=request.user.following.all())
    reviews_user = models.Review.objects.filter(user=request.user)
    reviews_user_follow = models.Review.objects.filter(user__in=request.user.following.all())
    reviews_follower = models.Review.objects.filter(user__in=request.user.follower.all())

    for ticket_user_follow in tickets_user_follow:

        """ Affiche le ticket de mes following avec réponse """
        if ticket_user_follow.response == '1':
            ticket_user_follow.entry_type = "Ticket_Response"

            for review_user in reviews_user:

                """Affiche la review de l'utilisateur connecté et le ticket des mes following """
                if review_user.ticket_id == ticket_user_follow.id:
                    review_user.entry_type = "Review"

            for review_user_follow in reviews_user_follow:
                for ticket_user in tickets_user:

                    """ Affiche la review et ticket de mes following """
                    if review_user_follow.ticket_id == ticket_user_follow.id:
                        review_user_follow.entry_type = "Review"

                    """Affiche la review de mes following et le ticket de l'utilisateur connecté """
                    if review_user_follow.ticket_id == ticket_user.id:
                        review_user_follow.entry_type = "Review"

        """ Affiche le ticket (sans réponse) de mes following """
        if ticket_user_follow.response == '0':
            ticket_user_follow.entry_type = "Ticket_Not_Response"

    for ticket_user in tickets_user:

        """ Affiche le ticket (sans réponse) de l'utilisateur connecté """
        if ticket_user.response == '0':
            ticket_user.entry_type = "Ticket_Not_Response"

        """ Affiche le ticket (avec réponse) de l'utilisateur connecté """
        if ticket_user.response == '1':
            ticket_user.entry_type = "Ticket_Response"
            for review_user in reviews_user:

                """ Affiche la review et ticket de l'utilisateur connecté """
                if review_user.ticket_id == ticket_user.id:
                    review_user.entry_type = "Review"

            for review_follower in reviews_follower:
                """ Affiche la review de mes followers du ticket de l'utilisateur connecté"""
                if review_follower.ticket_id == ticket_user.id:
                    review_follower.entry_type = "Review"

    entries = sorted(chain(tickets_user, tickets_user_follow, reviews_user, reviews_user_follow, reviews_follower),
                     key=lambda x: x.date_created, reverse=True)
    return render(request, 'blog/flow.html', context={'entries': entries})


@login_required
def posts(request):
    tickets_user = models.Ticket.objects.filter(user=request.user)
    tickets_user_follow = models.Ticket.objects.filter(user__in=request.user.following.all())
    reviews_user = models.Review.objects.filter(user=request.user)
    reviews_user_follow = models.Review.objects.filter(user__in=request.user.following.all())

    for ticket_user_follow in tickets_user_follow:
        if ticket_user_follow.response == '1':
            for review_user in reviews_user:

                """Affiche la review de l'utilisateur connecté et le ticket de mes following"""
                if review_user.ticket_id == ticket_user_follow.id:
                    review_user.entry_type = "Review_User_Ticket_Follow"

            for review_user_follow in reviews_user_follow:
                for ticket_user in tickets_user:

                    """Affiche la review de mes following et le ticket de l'utilisateur connecté"""
                    if review_user_follow.ticket_id == ticket_user.id:
                        review_user_follow.entry_type = "Review_Follow_Ticket_User"

    for ticket_user in tickets_user:

        """ Affiche le ticket ( avec réponse ) de l'utilisateur connecté """
        if ticket_user.response == '1':
            ticket_user.entry_type = "Ticket_User_Response"
            for review_user in reviews_user:

                """ Affiche la review et ticket de l'utilisateur connecté """
                if review_user.ticket_id == ticket_user.id:
                    review_user.entry_type = "Review_User_Ticket_User"

        """ Affiche le ticket ( sans réponse ) de l'utilisateur connecté """
        if ticket_user.response == '0':
            ticket_user.entry_type = "Ticket_User_Not_Response"

    entries = sorted(chain(tickets_user, tickets_user_follow, reviews_user, reviews_user_follow),
                     key=lambda x: x.date_created, reverse=True)
    return render(request, 'blog/posts.html', context={'entries': entries})


@login_required
def create_ticket(request):
    ticket_form = forms.TicketForm()
    photo_form = forms.PhotoForm()
    if request.method == 'POST':
        ticket_form = forms.TicketForm(request.POST)
        photo_form = forms.PhotoForm(request.POST, request.FILES)
        if all([ticket_form.is_valid(), photo_form.is_valid()]):
            photo = photo_form.save(commit=False)
            photo.uploader = request.user
            photo.save()
            ticket = ticket_form.save(commit=False)
            ticket.user = request.user
            ticket.photo = photo
            ticket.save()
            return redirect('flow')
    context1 = {
        'ticket_form': ticket_form,
        'photo_form': photo_form,
    }
    return render(request, 'blog/create_ticket.html', context=context1)


@login_required
def review_not_in_response(request):
    ticket_form = forms.TicketForm()
    review_form = forms.ReviewForm()
    photo_form = forms.PhotoForm()
    if request.method == 'POST':
        ticket_form = forms.TicketForm(request.POST)
        review_form = forms.ReviewForm(request.POST)
        photo_form = forms.PhotoForm(request.POST, request.FILES)
        if all([ticket_form.is_valid(), review_form.is_valid(), photo_form.is_valid()]):
            photo = photo_form.save(commit=False)
            photo.uploader = request.user
            photo.save()
            ticket = ticket_form.save(commit=False)
            ticket.user = request.user
            ticket.photo = photo
            ticket.response = 1
            ticket.save()
            review = review_form.save(commit=False)
            review.user = request.user
            review.ticket_id = ticket.id
            selected_rating = request.POST.getlist('rating')
            if selected_rating:
                review.rating = int(selected_rating[0])
                review.save()
                return redirect('flow')
            else:
                review.rating = 0
                review.save()
                return redirect('flow')
    context2 = {
        'review_form': review_form,
        'photo_form': photo_form,
        'ticket_form': ticket_form,
    }
    return render(request, 'blog/review_not_in_response.html', context=context2)


@login_required
def review_in_response(request, ticket_id):
    ticket = get_object_or_404(models.Ticket, id=ticket_id)
    edit_ticket_form = forms.TicketForm(instance=ticket)
    review_form = forms.ReviewForm()
    if request.method == 'POST':
        edit_ticket_form = forms.TicketForm(request.POST, instance=ticket)
        review_form = forms.ReviewForm(request.POST)
        ticket.response = 1
        edit_ticket_form.save()
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.user = request.user
            review.ticket = ticket
            selected_rating = request.POST.getlist('rating')
            if selected_rating:
                review.rating = int(selected_rating[0])
                review.save()
                return redirect('flow')
            else:
                review.rating = 0
                review.save()
                return redirect('flow')
    context3 = {
        'review_form': review_form,
        'ticket': ticket,
        'edit_ticket_form': edit_ticket_form,
    }
    return render(request, 'blog/review_in_response.html', context=context3)


@login_required
def edit_review_in_response(request, review_id):
    review = get_object_or_404(models.Review, id=review_id)
    edit_review_form = forms.ReviewForm(instance=review)
    tickets = models.Ticket.objects.all()
    for ticket in tickets:
        if ticket.id == review.ticket_id:
            ticket_id = ticket.id
            ticket = get_object_or_404(models.Ticket, id=ticket_id)
            edit_ticket_form = forms.TicketForm(instance=ticket)
            if request.method == 'POST':
                edit_review_form = forms.ReviewForm(request.POST, instance=review)
                edit_ticket_form = forms.TicketForm(request.POST, instance=ticket)
                edit_ticket_form.save()
                if edit_review_form.is_valid():
                    review = edit_review_form.save(commit=False)
                    review.user = request.user
                    review.ticket = ticket
                    select_rating = request.POST.getlist('rating')
                    if select_rating:
                        review.rating = int(select_rating[0])
                        review.save()
                        return redirect('posts')
                    else:
                        review.rating = 0
                        review.save()
                        return redirect('posts')
            context4 = {
                'edit_review_form': edit_review_form,
                'edit_ticket_form': edit_ticket_form,
                'ticket': ticket,
                'review': review,
            }

litreview/blog/templates/blog/create_ticket.html
<!-- create_ticket.html -->
{% extends 'base2.html' %}
{% load static %}
{% block head %}
        <meta charset="UTF-8">
        <title>Créer un ticket - LITReview.com</title>
        <link rel="stylesheet" type="text/css" href="{% static 'authentication/create_ticket.css' %}"/>
{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        <h2>Créer un ticket</h2>
        <fieldset>
            <p>
                <label for="id_title">Titre :</label>
                <input type="text" name="title" maxlength="128" required id="id_title">
            </p>
            <p>
                <label for="id_description">Description :</label>
                <textarea name="description" maxlength="5000" required id="id_description" rows="4" cols="50"></textarea>
            </p>
            <p>

                <label for="id_image">Image :</label>
                <input type="file" name="image" accept="image/*" required id="id_image">
            </p>
                <button type="submit">Envoyer</button>
        </fieldset>
    </form>
    {% endif %}
{% endblock %}

litreview/blog/templates/blog/edit_review_in_response.html
<!-- edit_review_in_response.html -->
{% extends 'base2.html' %}
{% load static %}
{% block head %}
        <meta charset="UTF-8">
        <title>Modifier une critique - LITReview.com</title>
        <link rel="stylesheet" type="text/css" href="{% static 'authentication/review_in_response.css' %}"/>
{% endblock %}
{% block content %}
        {% if user.is_authenticated %}
        <form method="post" enctype="multipart/form-data">{% csrf_token %}
                <h1>Modifier une critique</h1>
                <div class="rectangle1">
                    <p>Vous êtes en train de poster en réponse à : {{ ticket.user.username }} </p>
                    <div class="rectangle2">
                        <p class="user_date">{{ ticket.user.username }} a demandé une critique le {{ ticket.date_created }}</p>
                        <p>
                            <input type="hidden" name="title" value="{{ ticket.title }}">
                        </p>
                        <h2>{{ ticket.title }}</h2>
                        <p>{{ ticket.description }}</p>
                        <p>
                            <input type="hidden" name="description" value="{{ ticket.description }}">
                        </p>
                        <img alt="{{ ticket.title }}" src="{{ ticket.photo.image.url }}">
                    </div>
                </div>
                <div class="rectangle3">
                    <h3>Critique</h3>
                    <p>
                        <label for="id_headline">Titre</label>
                    </p>
                    <div>
                        <input type="text" name="headline" value="{{ review.headline }}" required id="id_headline">
                    </div>
                    <label class="rating">Note</label>
                    <div class="checkbox">
                        <input type="checkbox" id="id_checkbox0" name="rating" value="0"/>
                        <label for="id_checkbox0">-0</label>
                        <input type="checkbox" id="id_checkbox1" name="rating" value="1"/>
                        <label for="id_checkbox1">-1</label>
                        <input type="checkbox" id="id_checkbox2" name="rating" value="2"/>
                        <label for="id_checkbox2">-2</label>
                        <input type="checkbox" id="id_checkbox3" name="rating" value="3"/>
                        <label for="id_checkbox3">-3</label>
                        <input type="checkbox" id="id_checkbox4" name="rating" value="4"/>
                        <label for="id_checkbox4">-4</label>
                        <input type="checkbox" id="id_checkbox5" name="rating" value="5"/>
                        <label for="id_checkbox5">-5</label>
                    </div>
                    <p>
                        <label for="id_body">Commentaire</label>
                    </p>
                    <textarea name="body" maxlength="5000" required id="id_body" rows="4" cols="50">{{ review.body }}</textarea>
                    <button type="submit">Envoyer</button>
                </div>
        </form>
        {% endif %}
{% endblock %}

litreview/blog/templates/blog/edit_ticket_not_response.html
<!-- edit_ticket_not_response.html -->
{% extends 'base2.html' %}
{% load static %}
{% block head %}
        <meta charset="UTF-8">
        <title>Modifier votre ticket - LITReview.com</title>
        <link rel="stylesheet" type="text/css" href="{% static 'authentication/edit_ticket_not_response.css' %}"/>
{% endblock %}
{% block content %}
        {% if user.is_authenticated %}
        <form method="post" enctype="multipart/form-data">{% csrf_token %}
                <h1>Modifier votre ticket</h1>
                <div class="rectangle1">
                        <p>
                                <label for="id_title">Titre</label>
                        </p>
                        <div>
                                <input type="text" name="title" value="{{ ticket.title }}" required id="id_title">
                        </div>
                        <p>
                                <label for="id_description">Description</label>
                        </p>

                        <textarea name="description" maxlength="5000" required id="id_description" rows="4" cols="50">{{ ticket.description }}</textarea>
                        <p>
                                <label for="id_image">Image</label>
                                <input type="file" name="image" accept="image/*" required id="id_image">
                        </p>
                        <button type="submit">Envoyer</button>
                        <a class="button_cancel" href="{% url 'posts' %}">Annuler</a>
                </div>
        </form>
        {% endif %}
{% endblock %}

litreview/blog/templates/blog/edit_ticket_not_response1.html
<!-- edit_ticket_not_response1.html -->
{% extends 'base2.html' %}
{% load static %}
{% block head %}
        <meta charset="UTF-8">
        <title>Modifier votre ticket - LITReview.com</title>
        <link rel="stylesheet" type="text/css" href="{% static 'authentication/edit_ticket_not_response.css' %}"/>
{% endblock %}
{% block content %}
        {% if user.is_authenticated %}
        <form method="post" enctype="multipart/form-data">{% csrf_token %}
                <h1>Modifier votre ticket</h1>
                <div class="rectangle1">
                        <p>
                                <label for="id_title">Titre</label>
                        </p>
                        <div>
                                <input type="text" name="title" value="{{ ticket.title }}" required id="id_title">
                        </div>
                        <p>
                                <label for="id_description">Description</label>

                        </p>
                        <div>
                                <textarea name="description" maxlength="5000" required id="id_description" rows="4" cols="50">{{ ticket.description }}</textarea>
                        </div>

                        <img alt="{{ ticket.title }}" src="{{ ticket.photo.image.url }}">
                        <button type="submit">Envoyer</button>
                        <a class="button_cancel" href="{% url 'posts' %}">Annuler</a>
                </div>
        </form>
        {% endif %}
{% endblock %}

litreview/blog/templates/blog/flow.html
<!-- flow.html -->
{% extends 'base2.html' %}
{% load static %}
{% block head %}
        <meta charset="UTF-8">
        <title>Flux - LITReview.com</title>
        <link rel="stylesheet" type="text/css" href="{% static 'authentication/flow.css' %}"/>
{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
    <form method="post">{% csrf_token %}
        <nav class="critical_button">
            <a class="request_button" href="{% url 'create_ticket' %}">Demander une critique</a>
            <a class="create_button" href="{% url 'review_not_in_response' %}">Créer une critique</a>
        </nav>
        <fieldset>
            {% for entry in entries %}
            {% if entry.entry_type == "Ticket_Not_Response"%}
            {% include 'get_ticket_not_response_flow.html'%}
            {% endif %}

            {% if entry.entry_type == "Ticket_Response"%}
            {% include 'get_ticket_response_flow.html'%}
            {% endif %}

            {% if entry.entry_type == "Review"%}
            {% include 'get_review_ticket_flow.html'%}
            {% endif %}
            {% endfor %}
        </fieldset>
    </form>
    {% endif %}
{% endblock %}

litreview/blog/templates/blog/get_review_ticket_flow.html
<div class="rectangle1">
	<p class="user_date">{{ entry.user.username }} à publié une critique le {{ entry.date_created }}</p>
	<h2>{{ entry.headline }}</h2>

	{% if entry.rating == 5 %}
	<div class="star star-5"></div>
	<p class="body">{{ entry.body }}</p>

	{% elif entry.rating == 4 %}
	<div class="star star-4"></div>
	<p class="body">{{ entry.body }}</p>

	{% elif entry.rating == 3 %}
	<div class="star star-3"></div>
	<p class="body">{{ entry.body }}</p>

	{% elif entry.rating == 2 %}
	<div class="star star-2"></div>
	<p class="body">{{ entry.body }}</p>

	{% elif entry.rating == 1 %}
	<div class="star star-1"></div>
	<p class="body">{{ entry.body }}</p>

	{% elif entry.rating == 0 %}
	<div class="star star-0"></div>
	<p class="body">{{ entry.body }}</p>
	{% endif %}

	<div class="rectangle2">
		<p class="user_date">Ticket - {{ entry.ticket.user.username }}</p>
		<h2>{{ entry.ticket.title }}</h2>
		<p class="description">{{ entry.ticket.description }}</p>
		<img alt="{{ entry.ticket.title }}" src="{{ entry.ticket.photo.image.url }}">
	</div>
</div>

litreview/blog/templates/blog/get_ticket_not_response_flow.html
<div class="rectangle4">

	<p class="user_date">{{ entry.user.username }} a demandé une critique le {{entry.date_created }}</p>
	<h2>{{ entry.title }}</h2>
	<p class="description">{{ entry.description }}</p>
	<img alt="{{ entry.title }}" src="{{ entry.photo.image.url }}">
	<a class="create_button2" href="{% url 'review_in_response' entry.id %}">Créer une critique</a>
</div>

litreview/blog/templates/blog/get_ticket_response_flow.html
<div class="rectangle3">
	<p class="user_date">{{ entry.user.username }} a demandé une critique le {{ entry.date_created }}</p>
	<h2>{{ entry.title }}</h2>
	<p class="description">{{ entry.description }}</p>
	<img alt="{{ entry.title }}" src="{{ entry.photo.image.url }}">
</div>

litreview/blog/templates/blog/review_in_response.html
<!-- review_in_response.html -->
{% extends 'base2.html' %}
{% load static %}
{% block head %}
        <meta charset="UTF-8">
        <title>Créer une critique - LITReview.com</title>
        <link rel="stylesheet" type="text/css" href="{% static 'authentication/review_in_response.css' %}"/>
{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        <h1>Créer une critique</h1>
        <div class="rectangle1">
            <p>Vous êtes en train de poster en réponse à : {{ ticket.user.username }} </p>
            <div class="rectangle2">
                <p class="user_date">{{ ticket.user.username }} a demandé une critique le {{ ticket.date_created }}</p>
                <p>
                    <input type="hidden" name="title" value="{{ ticket.title }}">
                </p>
                <h2>{{ ticket.title }}</h2>
                <p>{{ ticket.description }}</p>
                <p>
                    <input type="hidden" name="description" value="{{ ticket.description }}">
                </p>
                <img alt="{{ ticket.title }}" src="{{ ticket.photo.image.url }}">


            </div>
        </div>
        <div class="rectangle3">
            <h3>Critique</h3>
            <p>
                <label for="id_headline">Titre</label>
            </p>
            <div>
                <input type="text" name="headline" required id="id_headline">
            </div>
            <label class="rating">Note</label>
            <div class="checkbox">
                <input type="checkbox" id="id_checkbox0" name="rating" value="0"/>
                <label for="id_checkbox0">-0</label>
                <input type="checkbox" id="id_checkbox1" name="rating" value="1"/>
                <label for="id_checkbox1">-1</label>
                <input type="checkbox" id="id_checkbox2" name="rating" value="2"/>
                <label for="id_checkbox2">-2</label>
                <input type="checkbox" id="id_checkbox3" name="rating" value="3"/>
                <label for="id_checkbox3">-3</label>
                <input type="checkbox" id="id_checkbox4" name="rating" value="4"/>
                <label for="id_checkbox4">-4</label>
                <input type="checkbox" id="id_checkbox5" name="rating" value="5"/>
                <label for="id_checkbox5">-5</label>

            </div>
            <p>
                <label for="id_body">Commentaire</label>
            </p>
            <textarea name="body" maxlength="5000" required id="id_body" rows="4" cols="50"></textarea>
            <button type="submit">Envoyer</button>

        </div>

    </form>
    {% endif %}
{% endblock %}

litreview/blog/templates/blog/review_not_in_response.html
<!-- review_not_in_response.html -->
{% extends 'base2.html' %}
{% load static %}
{% block head %}
        <meta charset="UTF-8">
        <title>Créer une critique - LITReview.com</title>
        <link rel="stylesheet" type="text/css" href="{% static 'authentication/review_not_in_response.css' %}"/>
{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        <h1>Créer une critique</h1>
        <div class="rectangle1">

            <p>
                <label for="id_title">Titre :</label>
                <input type="text" name="title" maxlength="128" required id="id_title">
            </p>
            <p>
                <label for="id_description">Description :</label>
                <textarea name="description" maxlength="5000" required id="id_description" rows="4" cols="50"></textarea>
            </p>
            <p>

                <label for="id_image">Image :</label>
                <input type="file" name="image" accept="image/*" required id="id_image">
            </p>
        </div>

        <div class="rectangle2">
            <h2>Critique</h2>
            <p>
                <label for="id_headline">Titre :</label>
            </p>
            <div>
                <input type="text" name="headline" required id="id_headline">
            </div>
            <label class="rating">Note :</label>
            <div class="checkbox">
                <input type="checkbox" id="id_checkbox0" name="rating" value="0"/>
                <label for="id_checkbox0">-0</label>
                <input type="checkbox" id="id_checkbox1" name="rating" value="1"/>
                <label for="id_checkbox1">-1</label>
                <input type="checkbox" id="id_checkbox2" name="rating" value="2"/>
                <label for="id_checkbox2">-2</label>
                <input type="checkbox" id="id_checkbox3" name="rating" value="3"/>
                <label for="id_checkbox3">-3</label>
                <input type="checkbox" id="id_checkbox4" name="rating" value="4"/>
                <label for="id_checkbox4">-4</label>
                <input type="checkbox" id="id_checkbox5" name="rating" value="5"/>
                <label for="id_checkbox5">-5</label>
            </div>
            <p>
                <label for="id_body">Commentaire :</label>
                <textarea name="body" maxlength="5000" required id="id_body" rows="4" cols="50"></textarea>
            </p>
            <button type="submit">Envoyer</button>
        </div>

    </form>
    {% endif %}
{% endblock %}